# Generated by Django 2.0 on 2018-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=1000)),
                ('task', models.CharField(max_length=250)),
                ('rating_m', models.CharField(max_length=250)),
                ('rating_a', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
