# Generated by Django 2.0 on 2018-07-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_annotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation_model',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='annotation_model',
            name='link',
        ),
        migrations.RemoveField(
            model_name='annotation_model',
            name='rating_a',
        ),
    ]
