# Generated by Django 2.0 on 2018-08-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_annotation', '0002_auto_20180729_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation_model',
            name='anno',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
