# Generated by Django 2.0 on 2018-08-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_annotation', '0003_annotation_model_anno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation_model',
            name='anno',
        ),
    ]
